export const FLEXIPAY_COOKIE = "flex-pay-cookie"
export const FLEXIPAY_URL = "https://api.flexipay.ng/api"
export const FLEXIPAY_VENDOR_URL = "https://vendor.flexipay.ng/"
export const FLEXIPAY_TOKEN = "flexi-user-token"
export const FLEXIPAY_REDIRECT = process.env.NODE_ENV === 'production' ? "https://flexipay.ng" : "http://localhost:3000"
export const FLEXIPAY_TWITTER = "https://twitter.com/@FlexiPayNG"
export const FLEXIPAY_FACEBOOK = "https://www.facebook.com/FlexiPayNG"
export const FLEXIPAY_INSTAGRAM = "https://www.instagram.com/FlexiPayNG"
export const FLEXIPAY_PHONE = "tel:+2349020130444"
export const FLEXIPAY_EMAIL = "mailto:hello@FlexiPay.ng"
export const FLEXIPAY_YOUTUBE = "https://www.youtube.com/channel/UCKgsy8ZzkQH7I4LPLMwPInA"
export const FLEXIPAY_TIKTOK = "https://www.tiktok.com/@flexipay.ng"
export const FLEXIPAY_WHATSAPP = "https://wa.me/+2349020130444"