export const FLEXIPAY_COOKIE = "flex-pay-cookie"
export const FLEXIPAY_URL = "https://api.flexipay.ng/api"
export const FLEXIPAY_VENDOR_URL = "https://vendor.flexipay.ng/auth/login"
export const FLEXIPAY_TOKEN = "flexi-user-token"
export const FLEXIPAY_REDIRECT = process.env.NODE_ENV === 'production' ? "https://flexipay.ng" : "http://localhost:3000"