# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Updating Flexipay user interface....
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        key_path: ${{ secrets.KEY_PATH }}
        port: 22
        script: /cmd/update_user_interface.sh
